version: "3.8"
services:
  carbon-service:
    container_name: myCarbonServiceContainer
    build: .
    image: karimdaw/carbon-service:${CARBON_SERVICE_VERSION}

    ports:
      - "80:8080"
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    container_name: myCarbonPostgresContainer
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    # ports:
    #   - ":5432" # Optional: expose PostgreSQL port for local development

volumes:
  postgres-data:
