name: Build and Push Docker Image

on:
  push:
    branches:
      - master # Adjust as necessary for your workflow
    tags:
      - "v*" # Trigger on semantic version tags like v1.0.3
      # testing tags last try

env:
  IMAGE_NAME: karimdaw/carbon-service

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version tag and short SHA
        id: prep
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION_TAG=${GITHUB_REF#refs/tags/}
            echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV
          fi
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV

      - name: Prepare tags
        run: |
          TAGS="${{ env.IMAGE_NAME }}:sha-${{ env.SHORT_SHA }}"
          if [ -n "${{ env.VERSION_TAG }}" ]; then
            TAGS="${TAGS},${{ env.IMAGE_NAME }}:${{ env.VERSION_TAG }}"
          fi
          echo "TAGS=$TAGS" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.TAGS }}
          build-args: |
            VERSION=${{ env.VERSION_TAG }}
            COMMIT_SHA=${{ env.SHORT_SHA }}

      - name: Image digest
        run: echo "The image digest is ${{ steps.docker_build.outputs.digest }}"
