name: Build and Push Docker Image

on:
  push:
    branches:
      - master # Adjust as necessary for your workflow
    tags:
      - "v*" # Trigger on semantic version tags like v1.0.3

env:
  IMAGE_NAME: karimdaw/carbon-service

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version tag
        id: version_tag
        run: |
          echo "VERSION_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.VERSION_TAG }}

      - name: Image digest
        run: echo "The image digest is ${{ steps.docker_build.outputs.digest }}"
